version: '2'
services:
  client:
    build: ./client    
    ports:
      - '3000:3000'
    volumes:
      - ./client:/client
    links:
      - server
    networks: 
      - webappnetwork
  server:
    build: ./server
#    env_file: ./server/.env
   # restart: always    
    ports:
      - '4000:4000'
    volumes: 
      - ./server/assets:/server/assets
      - ./server:/server
    depends_on:
      - mongo
    networks: 
      - webappnetwork
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks: 
      - webappnetwork
networks: 
  webappnetwork: 
    driver: bridge
